stereo_visual_odometry_node:
  ros__parameters:
    camera_optical_frame: "camera_optical_link",
    odom_frame: "odom",
    baseline: 0.537,
    leftCamK: [
      718.856, 0.0, 607.1928,
      0.0, 718.856, 185.2157,
      0.0, 0.0,   1.0
    ],
    rightCamK: [
      718.856, 0.0, 607.1928,
      0.0, 718.856, 185.2157,
      0.0, 0.0,   1.0
    ],
    debug: true